#ifndef _MLIBC_CONFIG_H
#define _MLIBC_CONFIG_H

#define __MLIBC_ANSI_OPTION 1
#define __MLIBC_BSD_OPTION 1
#define __MLIBC_POSIX_OPTION 1
#define __MLIBC_LINUX_OPTION 1
#define __MLIBC_INTL_OPTION 1
#define __MLIBC_ICONV_OPTION 1
#define __MLIBC_GLIBC_OPTION 1
#define __MLIBC_CRYPT_OPTION 1
#define __MLIBC_SYSDEP_HAS_BITS_SYSCALL_H 0
#define __MLIBC_BSD_OPTION 1

#endif // _MLIBC_CONFIG_H
